"""A saved system-ID package: the measured plant, and its own noise.

Fixtures are synthesized in the layout `save_package_to_netcdf`
writes — (lines, responses, ...) with the sysid settings as group
attributes — with planted values the assertions name. The plate's own
controller-written saves (skipped where stressdata is absent) hold
the layout against the controller's real writer; they are ours,
generated by `generate_plate_sysid.py`, not copied from anywhere.
"""

from __future__ import annotations

import os

import numpy as np
import pytest

import visualdynamics
from visualdynamics.io import rattlesnake

STRESS = os.path.join(os.path.dirname(__file__), '..', 'stressdata',
                      'plate')
REAL_PACKAGE = os.path.join(STRESS, 'sysid_data.nc4')
REAL_STREAM = os.path.join(STRESS, 'sysid_stream.nc4')


@pytest.fixture(autouse=True)
def decline_the_sysid_question(monkeypatch):
    """Importing a quiet-then-loud two-stream file now asks whether it
    is a system ID run; tests not about the question answer No, and
    the ones about it patch their own answer over this."""
    from PySide6.QtWidgets import QMessageBox

    monkeypatch.setattr(
        QMessageBox, 'question',
        staticmethod(lambda *a, **k: QMessageBox.StandardButton.No))

FS = 2048.0
FRAME = 256
LINES = FRAME // 2 + 1


def _write_package(path, noise_level=1e-8, with_indices=True):
    import netCDF4 as nc

    ds = nc.Dataset(str(path), 'w')
    g = ds.createGroup('Random')
    g.sysid_sample_rate = FS
    g.sysid_frame_size = FRAME
    g.createDimension('sysid_fft_lines', LINES)
    g.createDimension('sysid_control_channels', 2)
    g.createDimension('sysid_output_channels', 3)
    if with_indices:
        g.createDimension('control_channels', 2)
        var = g.createVariable('control_channel_indices', 'i4',
                               ('control_channels',))
        var[...] = [3, 6]
    shape3 = ('sysid_fft_lines', 'sysid_control_channels',
              'sysid_output_channels')
    for name, value in (('frf_data_real', 2.0), ('frf_data_imag', 0.5)):
        var = g.createVariable(name, 'f8', shape3)
        var[...] = np.full((LINES, 2, 3), value)
    var = g.createVariable('frf_coherence', 'f8',
                           ('sysid_fft_lines', 'sysid_control_channels'))
    var[...] = np.full((LINES, 2), 0.97)
    for prefix, n, driven in (('response', 'sysid_control_channels', 1e-4),
                              ('reference', 'sysid_output_channels', 4e-5)):
        for kind, level in ((f'{prefix}_cpsd', driven),
                            (f'{prefix}_noise_cpsd', noise_level)):
            for part in ('real', 'imag'):
                var = g.createVariable(f'{kind}_{part}', 'f8',
                                       ('sysid_fft_lines', n, n))
                size = 2 if n == 'sysid_control_channels' else 3
                var[...] = (np.broadcast_to(
                    np.eye(size) * level, (LINES, size, size))
                    if part == 'real' else np.zeros((LINES, size, size)))
    ds.close()
    return str(path)


def test_the_package_imports_its_four_readings(tmp_path):
    path = _write_package(tmp_path / 'sysid.nc4')
    assert rattlesnake.sniff(path)
    out = visualdynamics.import_file(path)
    frf = out['Random_frf']
    assert frf.num_records == 6, '2 responses x 3 drives'
    assert frf.response_dof[:3] == ['4', '4', '4'], \
        'hardware channel numbers, node-only — real, if incomplete'
    assert frf.reference_dof[0] == '9001', \
        'the file never says which channels the drives were'
    assert frf.abscissa[1] == pytest.approx(FS / FRAME), \
        'the line spacing comes from the sysid settings'
    assert frf.ordinate[0, 5] == pytest.approx(2.0 + 0.5j)
    coherence = out['Random_coherence']
    assert coherence.num_records == 2
    assert coherence.ordinate[0, 0] == pytest.approx(0.97)
    # the driven and ambient autospectra arrive as a PSD pair — the
    # ratio is a reading of the two, not a third object
    driven = out['Random_excitation_psds']
    quiet = out['Random_noise_psds']
    assert driven.num_records == quiet.num_records == 5
    assert driven.response_dof == ['4', '7', '9001', '9002', '9003']
    assert driven.ordinate[0, 3] == pytest.approx(1e-4)
    assert driven.ordinate[2, 3] == pytest.approx(4e-5)
    assert quiet.ordinate[0, 3] == pytest.approx(1e-8)


def test_the_pair_divides_to_the_planted_ratio(tmp_path):
    """Driven 1e-4 over ambient 1e-8 is 40 dB, at every line, on the
    response channels; the drives plant 36 dB the same way — read
    through density_ratio, the one rule under every ratio view."""
    from visualdynamics.core.data import density_ratio

    path = _write_package(tmp_path / 'sysid.nc4')
    out = visualdynamics.import_file(path)
    _x, rows, dofs, _dims = density_ratio(out['Random_excitation_psds'],
                                   out['Random_noise_psds'])
    assert dofs == ['4', '7', '9001', '9002', '9003']
    response_db = 10 * np.log10(np.real(rows[0, 1:]))
    assert np.allclose(response_db, 40.0), 'the planted response ratio'
    drive_db = 10 * np.log10(np.real(rows[2, 1:]))
    assert np.allclose(drive_db, 10 * np.log10(4e-5 / 1e-8))


def test_silent_ambient_reads_as_no_ratio_not_infinity(tmp_path):
    """A simulated run measures perfect silence; a zero ambient line
    has nothing to divide by and answers NaN, never infinity."""
    from visualdynamics.core.data import density_ratio

    path = _write_package(tmp_path / 'sysid.nc4', noise_level=0.0)
    out = visualdynamics.import_file(path)
    _x, rows, _dofs, _dims = density_ratio(out['Random_excitation_psds'],
                                    out['Random_noise_psds'])
    assert np.all(np.isnan(np.real(rows)))


def test_the_package_survives_a_project_and_the_native_format(tmp_path):
    path = _write_package(tmp_path / 'sysid.nc4')
    project = visualdynamics.Project('sysid')
    project.import_file(path)
    pair = [name for name in project.names if 'PSD' in name]
    assert len(pair) == 2, 'the driven and ambient densities'
    saved = str(tmp_path / 'sysid.vdyn')
    project.save(saved)
    back = visualdynamics.Project.open(saved)
    for name in pair:
        assert np.allclose(np.real(back[name].ordinate),
                           np.real(project[name].ordinate),
                           equal_nan=True)


@pytest.mark.skipif(not os.path.exists(REAL_PACKAGE),
                    reason='plate stressdata not on this machine')
def test_the_plate_package_holds_the_layout():
    """The controller's own writer produced this file — against the
    plate's plant, 8 control accelerometers and 4 drives; reading it
    is the layout check no synthesized fixture can be."""
    out = visualdynamics.import_file(REAL_PACKAGE)
    frf = out['Random_frf']
    assert frf.num_records == 32, '8 responses x 4 drives'
    assert frf.reference_dof[0] == '9001', 'synthetic drive numbering'
    assert frf.abscissa[1] == pytest.approx(2.0), \
        'sysid frame 2048 at 4096 Hz'
    assert out['Random_coherence'].num_records == 8
    from visualdynamics.core.data import density_ratio

    _x, rows, _dofs, _dims = density_ratio(out['Random_excitation_psds'],
                                    out['Random_noise_psds'])
    assert rows.shape[0] == 12, '8 responses and 4 drives'
    response_db = 10 * np.log10(np.real(rows[:8, 1:]))
    assert 15.0 < np.nanmedian(response_db) < 60.0, \
        'the responses ride the injected noise floor: finite, visible'
    assert np.all(np.isnan(np.real(rows[8:]))), \
        'the drives are clean — nothing injects noise on the outputs'


@pytest.mark.skipif(not os.path.exists(REAL_STREAM),
                    reason='plate stressdata not on this machine')
def test_the_plate_stream_holds_the_two_phases():
    """The streamed save from the same run: the ambient phase as
    `time_data`, the driven phase as the restarted stream — and the
    file declares its environment, not "system ID", which is exactly
    why the project type stays a manual choice for this form."""
    assert rattlesnake.project_type(REAL_STREAM) == 'Random Vibration'
    assert rattlesnake.streamed_sysid_candidate(REAL_STREAM), \
        'the real save is exactly the shape the import question is for'
    out = visualdynamics.import_file(REAL_STREAM)
    quiet, driven = out['time_data'], out['time_data_2']
    assert quiet.num_records == driven.num_records == 12
    assert 0.0 < float(quiet.ordinate.std()) < 0.01, \
        'the ambient phase measured the injected noise floor'
    assert float(driven.ordinate.std()) > 0.1, \
        'the driven phase carries the excitation'
    project = visualdynamics.Project('sysid')
    project.import_file(REAL_STREAM)
    quiet_history = project['Time History']
    quiet_history.averaging = None
    driven_psds = project[project.compute_psds('Time History (2)')]
    quiet_history.averaging = \
        project['Time History (2)'].averaging
    quiet_psds = project[project.compute_psds('Time History')]
    from visualdynamics.core.data import density_ratio

    _x, rows, _dofs, _dims = density_ratio(driven_psds, quiet_psds)
    db = 10 * np.log10(np.real(rows[:8, 5:-5]))
    assert 15.0 < np.nanmedian(db) < 60.0, \
        'the workflow reads a finite ratio out of the real save'


# ---- the other save: time data, two streams -----------------------------

def _write_streamed_sysid(path, seconds=4.0, fs=2048.0, snr_db=30.0,
                          seed=3, with_spec=False):
    """A system-ID run saved as time data: the streaming layout, with
    the ambient noise as the first stream and the driven excitation
    as the second — CREATE_NEW_STREAM's `time_data_1`. `with_spec`
    adds the Random environment and its specification, the way a real
    sysid stream carries its environment's requirement."""
    import netCDF4 as nc

    rng = np.random.default_rng(seed)
    samples = int(seconds * fs)
    noise_rms = 0.1
    driven_rms = noise_rms * 10 ** (snr_db / 20)
    ds = nc.Dataset(str(path), 'w')
    ds.file_version = '3.0.0'
    ds.sample_rate = fs
    ds.createDimension('response_channels', 2)
    ds.createDimension('time_samples', samples)
    ds.createDimension('time_samples_1', samples)
    quiet = ds.createVariable('time_data', 'f8',
                              ('response_channels', 'time_samples'))
    quiet[...] = rng.standard_normal((2, samples)) * noise_rms
    driven = ds.createVariable('time_data_1', 'f8',
                               ('response_channels', 'time_samples_1'))
    driven[...] = rng.standard_normal((2, samples)) * driven_rms
    ch = ds.createGroup('channels')
    ch.createDimension('n', 2)
    for name, column in (('node_number', ['101', '104']),
                         ('node_direction', ['Z+', 'Z+']),
                         ('unit', ['m/s^2', 'm/s^2']),
                         ('feedback_device', ['', ''])):
        var = ch.createVariable(name, str, ('n',))
        for i, value in enumerate(column):
            var[i] = value
    if with_spec:
        ds.createDimension('num_environments', 1)
        ds.createVariable('environment_names', str,
                          ('num_environments',))[0] = 'Random'
        types = ds.createVariable('environment_types', int,
                                  ('num_environments',))
        types[0] = 1
        g = ds.createGroup('Random')
        g.samples_per_frame = 512
        g.frames_in_cpsd = 6
        g.cpsd_overlap = 0.5
        g.cpsd_window = 'hann'
        g.createDimension('control_channels', 2)
        g.createDimension('lines', 4)
        g.createVariable('control_channel_indices', 'i4',
                         ('control_channels',))[...] = [0, 1]
        g.createVariable('specification_frequency_lines', 'f8',
                         ('lines',))[...] = [50.0, 100.0, 200.0, 400.0]
        for name in ('specification_cpsd_matrix_real',
                     'specification_cpsd_matrix_imag'):
            var = g.createVariable(
                name, 'f8', ('lines', 'control_channels',
                             'control_channels'))
            var[...] = np.broadcast_to(
                np.eye(2) * 1e-3 if 'real' in name
                else np.zeros((2, 2)), (4, 2, 2))
    ds.close()
    return str(path)


def test_every_stream_imports_not_just_the_first(tmp_path):
    path = _write_streamed_sysid(tmp_path / 'sysid_stream.nc4')
    out = visualdynamics.import_file(path)
    assert 'time_data' in out and 'time_data_2' in out, \
        'the driven excitation is the second stream, and it used to vanish'
    assert out['time_data_2'].ordinate.std() > \
        10 * out['time_data'].ordinate.std(), \
        'the driven stream is the loud one'


def test_the_streams_densities_read_the_planted_ratio(tmp_path):
    """Broadband driven at 30 dB over broadband ambient: compute the
    two PSDs, divide, read the planted number back — the workflow as
    a script, exactly as the app's Ratio reading does it."""
    from visualdynamics.core.data import density_ratio

    path = _write_streamed_sysid(tmp_path / 'sysid_stream.nc4')
    project = visualdynamics.Project('sysid')
    project.import_file(path)
    driven_psds = project[project.compute_psds('Time History (2)')]
    project['Time History'].averaging = \
        project['Time History (2)'].averaging
    quiet_psds = project[project.compute_psds('Time History')]
    _x, rows, dofs, _dims = density_ratio(driven_psds, quiet_psds)
    db = 10 * np.log10(np.real(rows[:, 5:-5]))
    assert np.median(db) == pytest.approx(30.0, abs=1.0)
    assert dofs == ['101Z+', '104Z+']


def test_density_ratio_refuses_disjoint_channels():
    from visualdynamics.core.data import Psd, density_ratio

    freq = np.linspace(1.0, 100.0, 50)
    a = Psd(abscissa=freq, ordinate=np.ones((1, 50)),
            response_dof=['101Z+'])
    b = Psd(abscissa=freq, ordinate=np.ones((1, 50)),
            response_dof=['999X+'])
    with pytest.raises(ValueError, match='share no'):
        density_ratio(a, b)


def test_density_ratio_refuses_mismatched_lines():
    from visualdynamics.core.data import Psd, density_ratio

    a = Psd(abscissa=np.linspace(1.0, 100.0, 50),
            ordinate=np.ones((1, 50)), response_dof=['101Z+'])
    b = Psd(abscissa=np.linspace(1.0, 200.0, 50),
            ordinate=np.ones((1, 50)), response_dof=['101Z+'])
    with pytest.raises(ValueError, match='frequency lines'):
        density_ratio(a, b)


def test_any_number_of_streams_import_in_order(tmp_path):
    """A run can stop and restart its stream as often as it likes —
    system ID makes two, but nothing limits the count. Twelve
    streams, each louder than the last, import in stream order —
    twelve rather than a few because double digits are where a
    string sort would slide _10 in between _1 and _2."""
    from itertools import pairwise

    import netCDF4 as nc

    path = str(tmp_path / 'many.nc4')
    ds = nc.Dataset(path, 'w')
    ds.file_version = '3.0.0'
    ds.sample_rate = 1024.0
    ds.createDimension('response_channels', 1)
    rng = np.random.default_rng(11)
    for k in range(12):
        suffix = '' if k == 0 else f'_{k}'
        ds.createDimension(f'time_samples{suffix}', 512)
        var = ds.createVariable(f'time_data{suffix}', 'f8',
                                ('response_channels',
                                 f'time_samples{suffix}'))
        var[...] = rng.standard_normal((1, 512)) * 2.0 ** k
    ch = ds.createGroup('channels')
    ch.createDimension('n', 1)
    for name, value in (('node_number', '101'), ('node_direction', 'Z+'),
                        ('unit', 'm/s^2'), ('feedback_device', '')):
        var = ch.createVariable(name, str, ('n',))
        var[0] = value
    ds.close()

    out = visualdynamics.import_file(path)
    keys = ['time_data'] + [f'time_data_{k}' for k in range(2, 13)]
    assert [key for key in out if key.startswith('time_data')] == keys
    levels = [float(out[key].ordinate.std()) for key in keys]
    assert all(b > 1.5 * a for a, b in pairwise(levels)), \
        'stream order held: each one louder than the one before'


def test_two_selected_densities_offer_the_ratio_reading(window, pump):
    """Two plain PSDs selected together read two ways — overlaid, or
    divided in decibels (Brandon, 2026-08-25). The bar offers the
    pair; the ratio draws the louder over the quieter with a linear
    frequency axis, like nearly every plot here."""
    import pyqtgraph as pg

    from visualdynamics.core.data import Psd

    freq = np.linspace(2.0, 1000.0, 500)
    quiet = Psd(abscissa=freq, ordinate=np.full((2, 500), 1e-6),
                response_dof=['101Z+', '104Z+'],
                ordinate_dim=['acceleration**2/frequency'] * 2)
    loud = Psd(abscissa=freq, ordinate=np.full((2, 500), 1e-3),
               response_dof=['101Z+', '104Z+'],
               ordinate_dim=['acceleration**2/frequency'] * 2)
    window.add_object('Noise PSDs', quiet)
    window.add_object('Excitation PSDs', loud)
    pane = window.data_pane
    pane.waterfall_action.setChecked(False)
    window._item_for_object('Noise PSDs').setSelected(True)
    window._item_for_object('Excitation PSDs').setSelected(True)
    pump()
    assert pane.spectra_actions['ratio'].isVisible(), \
        'the pair earns the reading'
    assert pane.spectra_actions['overlay'].isChecked(), \
        'overlaid stays the default'
    pane.spectra_actions['ratio'].trigger()
    pump()
    plot = next(item for item in pane.graphics.ci.items
                if isinstance(item, pg.PlotItem))
    curves = [c for c in plot.listDataItems()
              if getattr(c, 'name', lambda: None)()]
    assert len(curves) == 2, 'one curve per shared channel'
    x, y = curves[0].getData()
    assert np.nanmax(x) == pytest.approx(1000.0), \
        'linear frequency, not a logged axis'
    assert np.allclose(y[np.isfinite(y)], 30.0), \
        'a thousandfold power ratio reads 30 dB'
    # a lone PSD, or three, does not offer it
    window.tree.clearSelection()
    window._item_for_object('Noise PSDs').setSelected(True)
    pump()
    assert not pane.spectra_actions['ratio'].isVisible()


# ---- the question a two-stream file earns -------------------------------

def test_quiet_then_loud_two_streams_earn_the_question(tmp_path):
    from visualdynamics.io.rattlesnake import streamed_sysid_candidate

    path = _write_streamed_sysid(tmp_path / 'sysid_stream.nc4')
    assert streamed_sysid_candidate(path)


def test_matched_levels_and_extra_streams_do_not(tmp_path):
    """A run that stopped and restarted its stream once has two halves
    at one level; a run with three streams is not the two-phase shape;
    a spectral package has no streams at all."""
    from visualdynamics.io.rattlesnake import streamed_sysid_candidate

    same = _write_streamed_sysid(tmp_path / 'same.nc4', snr_db=0.0)
    assert not streamed_sysid_candidate(same)

    import netCDF4 as nc

    three = _write_streamed_sysid(tmp_path / 'three.nc4')
    with nc.Dataset(three, 'a') as ds:
        ds.createDimension('time_samples_2', 64)
        var = ds.createVariable('time_data_2', 'f8',
                                ('response_channels', 'time_samples_2'))
        var[...] = np.zeros((2, 64))
    assert not streamed_sysid_candidate(three)

    package = _write_package(tmp_path / 'package.nc4')
    assert not streamed_sysid_candidate(package)


def test_answering_yes_types_the_project(window, pump, tmp_path,
                                         monkeypatch):
    from PySide6.QtWidgets import QMessageBox

    asked = []

    def question(_parent, title, text, *args, **kwargs):
        asked.append((title, text))
        return QMessageBox.StandardButton.Yes

    monkeypatch.setattr(QMessageBox, 'question', staticmethod(question))
    path = _write_streamed_sysid(tmp_path / 'sysid_stream.nc4',
                                 with_spec=True)
    window.import_paths([path])
    pump()
    assert len(asked) == 1
    assert 'System ID' in asked[0][1]
    assert window.project_type == 'System ID'
    # and the two phases are called what they are, told apart by
    # level — the quiet stream is the noise measurement
    assert 'Noise Time History' in window.objects
    assert 'Excitation Time History' in window.objects
    assert (window.objects['Excitation Time History'].ordinate.std()
            > window.objects['Noise Time History'].ordinate.std())
    item = window._item_for_object('Excitation Time History')
    assert item is not None and item.text(0) == 'Excitation Time History'
    # the renamed pair fills the skeleton's own slots of those names
    from visualdynamics.core.report import missing_expectations
    missing = [name for name, *_rest in missing_expectations(
        'System ID', window.objects, window.project.placed())]
    assert 'Noise Time History' not in missing
    assert 'Excitation Time History' not in missing
    # one file is one measurement: the run's specification joins the
    # group its histories landed in — the rename used to leave the
    # linking asking for the old names, and the join quietly refused
    group = next(g for g in window.links
                 if 'Noise Time History' in g['members'])
    assert 'Excitation Time History' in group['members']
    spec_names = [name for name, obj in window.objects.items()
                  if type(obj).__name__ == 'Specification']
    assert spec_names and all(name in group['members']
                              for name in spec_names), \
        'the specification belongs to the same measurement'
    # a second system ID in the same project numbers its pair rather
    # than colliding
    window.import_paths([_write_streamed_sysid(tmp_path / 'again.nc4')])
    pump()
    assert 'Noise Time History (2)' in window.objects
    assert 'Excitation Time History (2)' in window.objects


def test_answering_no_keeps_the_files_own_type(window, pump, tmp_path,
                                               monkeypatch):
    from PySide6.QtWidgets import QMessageBox

    asked = []
    monkeypatch.setattr(
        QMessageBox, 'question',
        staticmethod(lambda *a, **k: asked.append(a)
                     or QMessageBox.StandardButton.No))
    path = _write_streamed_sysid(tmp_path / 'sysid_stream.nc4')
    window.import_paths([path])
    pump()
    assert len(asked) == 1
    assert window.project_type is None, \
        'declined, and this synthesized stream names no environment'


def test_a_project_already_system_id_is_not_asked(window, pump, tmp_path,
                                                  monkeypatch):
    """The question exists to catch a type the file got wrong; once the
    project says System ID there is nothing left to ask."""
    from PySide6.QtWidgets import QMessageBox

    asked = []
    monkeypatch.setattr(
        QMessageBox, 'question',
        staticmethod(lambda *a, **k: asked.append(a)
                     or QMessageBox.StandardButton.Yes))
    window.import_paths([_write_package(tmp_path / 'package.nc4')])
    pump()
    assert window.project_type == 'System ID' and not asked
    window.import_paths([_write_streamed_sysid(tmp_path / 'stream.nc4')])
    pump()
    assert not asked, 'the streams joined a project that already knew'


def test_an_import_draws_once_not_per_selection_change(window, pump,
                                                       tmp_path,
                                                       monkeypatch):
    """Importing this file used to render 48 times — every object
    added and every tree reshuffle of the type switch moved the
    selection, and each move rebuilt the view, 31 of them the
    specification's whole 3D stage in front of the user. The import
    suppresses selection renders and draws the final state once."""
    from PySide6.QtWidgets import QMessageBox

    monkeypatch.setattr(QMessageBox, 'question', staticmethod(
        lambda *a, **k: QMessageBox.StandardButton.Yes))
    calls = []
    real = window.render_current
    monkeypatch.setattr(
        window, 'render_current',
        lambda *a, **k: (calls.append(1), real(*a, **k))[1])
    window.import_paths([_write_streamed_sysid(tmp_path / 's.nc4')])
    pump()
    assert len(calls) == 1, \
        f'{len(calls)} renders for one import; the storm is back'
    assert window.project_type == 'System ID'


# ---- the project type ---------------------------------------------------

def test_a_spectral_package_declares_itself_system_id(tmp_path):
    path = _write_package(tmp_path / 'sysid.nc4')
    assert rattlesnake.project_type(path) == 'System ID'
    project = visualdynamics.Project('run')
    project.import_file(path)
    assert project.project_type == 'System ID'


def test_a_streamed_sysid_save_keeps_its_environment_type(tmp_path):
    """A stream from a sysid run is indistinguishable from a run of
    its environment; the person switches the type, the file cannot."""
    path = _write_streamed_sysid(tmp_path / 'stream.nc4')
    assert rattlesnake.project_type(path) is None, \
        'this synthesized stream names no environments at all'


def test_the_sysid_report_renders_from_a_package(tmp_path):
    import json

    from visualdynamics.report import render_html

    path = _write_package(tmp_path / 'sysid.nc4')
    project = visualdynamics.Project('run')
    project.import_file(path)
    project.set_basis(*list(project))
    name = project.generate_report('sysid')
    html = render_html(project[name], project)
    payload = json.loads(html.split('type="application/json">')[1]
                         .split('</script>')[0])
    captions = [block.get('caption', '') for block in payload['blocks']]
    # no CMIF: a system ID identifies a plant rather than counting
    # modes (Brandon, 2026-08-23). The densities overlaid, the
    # coherence and the ratio are the readings.
    assert not any('Indicator' in c for c in captions)
    assert any('densities overlaid' in c for c in captions)
    assert any('Signal to noise' in c for c in captions)
    # the coherence reads on the stage too now (Brandon), so the
    # figures a package renders are stage figures, not a map
    assert any(block.get('kind') == 'stage'
               for block in payload['blocks']), \
        'the coherence and the ratio are 3-D readings'
    assert not any('Drive point' in c for c in captions), \
        'a package has no drive points; that block stays an unbound slot'


def test_the_sysid_slots_serve_both_save_forms(window, pump):
    """The setup slots are optional (a spectral package has none of
    them); the three measured readings are required."""
    from visualdynamics.core.report import project_expectations

    expectations = project_expectations('System ID')
    names = [name for name, *_rest in expectations]
    # every slot named for its type (2026-09-02): the noise and the
    # excitation recordings are two Time History slots, their densities
    # two PSD slots — which is which is the order, noise first
    assert names == ['Geometry', 'Photos', 'Channel Table',
                     'Time History', 'Time History', 'PSD', 'PSD',
                     'FRF', 'Multiple Coherence', 'Report']
    optional = [opt for _name, _cls, _icon, _count, opt, _group
                in expectations]
    assert optional == [True] * 5 + [False] * 5, (
        'the setup and the two recordings are optional; the readings '
        'are required')
    counts = [count for _name, _cls, _icon, count, _opt, _group
              in expectations]
    assert counts[4] == 2, \
        'the second recording is the second TimeHistory'
    assert counts[6] == 2, \
        'and its density is the second Psd — the ratio is a reading ' \
        'of the two, never a third object in the tree'




def test_a_specification_never_fills_a_density_slot(tmp_path):
    """Delete both PSDs from a System ID project holding the stream's
    imported specification, and both PSD slots must come back gray —
    the spec slid past the per-type narrowing into the noise slot,
    because the type expects no Specification for the narrowing to
    key on (Brandon caught it deleting the demo's PSDs)."""
    from visualdynamics.core.data import Psd, Specification
    from visualdynamics.core.report import missing_expectations

    freq = np.linspace(2.0, 1000.0, 50)
    objects = {
        'Specification': Specification(
            abscissa=freq, ordinate=np.full((2, 50), 1e-3),
            response_dof=['101Z+', '104Z+'],
            ordinate_dim=['acceleration**2/frequency'] * 2),
    }
    missing = [name for name, *_rest in missing_expectations(
        'System ID', objects)]
    assert missing.count('PSD') == 2, 'both density slots stay gray'
    # and a real density still fills its slot
    objects['PSDs'] = Psd(
        abscissa=freq, ordinate=np.full((2, 50), 1e-4),
        response_dof=['101Z+', '104Z+'],
        ordinate_dim=['acceleration**2/frequency'] * 2)
    missing = [name for name, *_rest in missing_expectations(
        'System ID', objects)]
    assert missing.count('PSD') == 1, 'one density fills one slot'


def test_the_sysid_report_shows_noise_then_excitation(window, pump,
                                                      tmp_path,
                                                      monkeypatch):
    """The time data reads in the run's own order (Brandon,
    2026-08-23): the ambient stream first, then the driven one, each
    its own figure so each draws under its own averaging frames — one
    combined figure could only carry one window."""
    from PySide6.QtWidgets import QMessageBox

    from visualdynamics.core.report import sysid_template

    monkeypatch.setattr(
        QMessageBox, 'question',
        staticmethod(lambda *a, **k: QMessageBox.StandardButton.Yes))
    path = _write_streamed_sysid(tmp_path / 'sysid.nc4')
    window.import_paths([path])
    pump()
    assert 'Noise Time History' in window.objects

    report = sysid_template(dict(window.objects),
                            links=window.project.links)
    time_plots = [b for b in report.blocks if b.get('kind') == 'plot'
                  and 'Time History' in str(b.get('source'))]
    assert [b['source'] for b in time_plots] == \
        ['Noise Time History', 'Excitation Time History'], \
        'quiet stream first, bound by name'
    assert 'noise' in time_plots[0]['caption']
    assert 'frames' in time_plots[0]['caption'], 'windowing promised'


def test_a_mixed_stream_splits_into_one_figure_per_type():
    """Force and acceleration channels must not share a time axis
    (Brandon, 2026-08-23 — one plot per type): a stream carrying both
    gets one figure per quantity, excitation types first, for each of
    the two streams."""
    from visualdynamics.core.data import TimeHistory
    from visualdynamics.core.report import sysid_template

    t = np.arange(64) / 64.0

    def stream(scale):
        return TimeHistory(
            t, np.ones((3, len(t))) * scale,
            response_dof=['9001X+', '101Z+', '104Z+'],
            ordinate_dim=['force', 'acceleration', 'acceleration'],
            ordinate_unit=['N', 'm/s**2', 'm/s**2'])

    report = sysid_template({'Noise': stream(0.01),
                             'Excitation': stream(1.0)})
    plots = [b for b in report.blocks if b.get('kind') == 'plot'
             and b.get('source') in ('Noise', 'Excitation')]
    assert [(b['source'], b.get('select')) for b in plots] == [
        ('Noise', 'dim:force'), ('Noise', 'dim:acceleration'),
        ('Excitation', 'dim:force'), ('Excitation', 'dim:acceleration')]
    assert 'force' in plots[0]['caption']
    assert 'noise' in plots[0]['caption']


def test_the_densities_overlay_per_quantity_and_pair_by_channel():
    """The noise and excitation densities read together, one figure
    per quantity (Brandon, 2026-08-23) — the driven level solid and
    the ambient one dashed in the same color, so a channel and its
    own floor are one pair. No CMIF: a system ID identifies a plant,
    it does not count modes."""
    from visualdynamics.core.data import Psd
    from visualdynamics.core.report import sysid_template
    from visualdynamics.report import _build_block

    f = np.arange(1.0, 9.0)

    def densities(scale):
        return Psd(f, np.ones((3, len(f))) * scale,
                   response_dof=['9001X+', '101Z+', '104Z+'],
                   ordinate_dim=['force**2/frequency',
                                 'acceleration**2/frequency',
                                 'acceleration**2/frequency'],
                   ordinate_unit=['N', 'm/s**2', 'm/s**2'])

    objects = {'Noise PSDs': densities(1e-4),
               'Excitation PSDs': densities(1.0)}
    report = sysid_template(objects)
    assert not [b for b in report.blocks if b.get('mode') == 'cmif'], \
        'the CMIF is gone from this report'
    # the pair reads on the stage now, one figure per quantity
    # (Brandon, 2026-08-23) — the app's own 3-D overlay
    pairs = [b for b in report.blocks
             if b.get('floor') and b.get('reading') != 'ratio']
    assert [b['quantity'] for b in pairs] == ['force', 'acceleration']
    assert all(b['mode'] == 'stage' for b in pairs)
    assert all(b['source'] == 'Excitation PSDs'
               and b['floor'] == 'Noise PSDs' for b in pairs), \
        'the louder set leads, as it does in the ratio below'
    # the ratio still follows, reading the same pair
    ratio = next(b for b in report.blocks
                 if b.get('reading') == 'ratio')
    assert (ratio['source'], ratio['floor']) == ('Excitation PSDs',
                                                 'Noise PSDs')
    assert report.blocks.index(pairs[-1]) < report.blocks.index(ratio)

    # a stage block answers with the figures it needs; this pair is
    # two channels, so one
    figures = _build_block(pairs[1], objects, visualdynamics.SI, [])
    assert len(figures) == 1
    built = figures[0]
    assert built['kind'] == 'stage'
    assert [r.get('quiet', False) for r in built['runs']] == [
        False, True, False, True], \
        'each station meets its pair: the louder, then the stood-back'
    assert built['labels'][:2] == ['101Z+', '101Z+'], \
        'the acceleration channels only, both sides of each station'


def test_a_silent_channel_is_not_a_legend_entry():
    """The ambient recording of a drive channel is exactly zero — the
    shaker was off — and zero has no place on a log axis. A legend
    entry for a curve that draws nothing is a claim the figure does
    not support, so the curve goes and the caption says why."""
    from visualdynamics.core.data import Psd
    from visualdynamics.report import _build_block

    f = np.arange(1.0, 9.0)
    quiet = Psd(f, np.zeros((1, len(f))), response_dof=['9001X+'],
                ordinate_dim='force**2/frequency', ordinate_unit='N')
    loud = Psd(f, np.ones((1, len(f))), response_dof=['9001X+'],
               ordinate_dim='force**2/frequency', ordinate_unit='N')
    objects = {'Noise': quiet, 'Excitation': loud}
    block = {'kind': 'plot', 'mode': 'pair', 'source': 'Excitation',
             'floor': 'Noise', 'caption': 'Densities overlaid'}
    built = _build_block(block, objects, visualdynamics.SI, [])
    assert [c['label'] for c in built['curves']] == ['Excitation: 9001X+']
    assert 'recorded exactly zero' in built['caption']

    # and with both sides real, nothing is dropped and nothing is said
    objects['Noise'] = Psd(f, np.full((1, len(f)), 1e-6),
                           response_dof=['9001X+'],
                           ordinate_dim='force**2/frequency',
                           ordinate_unit='N')
    built = _build_block(block, objects, visualdynamics.SI, [])
    assert len(built['curves']) == 2
    assert built['caption'] == 'Densities overlaid'
