#!/usr/bin/env python
"""Cut the example projects into the zips the website links, and
upload them to the `examples` release.

    ./.venv/bin/python tools/cut_examples.py            # zips into dist/examples/
    ./.venv/bin/python tools/cut_examples.py --upload   # ...and onto the release

The projects live in `stressdata/`, gitignored and regenerable from
the generators (testdata/generate_plate_projects.py and
generate_drone_projects.py), so they are not in any package: the
installers stay small (Brandon, 2026-09-14) and the six plate projects
and four drone projects go up as two zips on a GitHub release of
their own, which the downloads page links. A release rather than the
site because Cloudflare Pages refuses a file over 25 MB; a release of
its own rather than the application's because the examples are cut
again whenever the project format moves — the `.vdyn` they hold is
provisional, and the next alpha's `.escdf` re-cuts them without
touching an application tag. `modal_hard` stays out: 5 GB exists to
stress the fitter, not to be downloaded.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import zipfile

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
REPO = 'visualdynamics/visualdynamics'
#: the release the zips live on, and the page's link target
TAG = 'examples'
URL = f'https://github.com/{REPO}/releases/download/{TAG}/'

#: asset name -> (the folder under stressdata/, the projects it takes,
#: one sentence for the zip's own README)
SETS = {
    'VisualDynamics-examples-plate.zip': (
        'plate_projects',
        ('modal', 'random', 'shock', 'sine', 'sysid', 'transient'),
        ('The plate: a rectangular plate, one project per workflow — '
         'the same data the website\'s figures and the guide\'s '
         'screenshots come from.')),
    'VisualDynamics-examples-drone.zip': (
        'drone_projects',
        ('modal', 'random', 'shock', 'transient'),
        ('The quadcopter: the same workflows on a model with the node '
         'count of a real test article.')),
}

README = """Visual Dynamics example projects — {title}

{sentence}

{listing}
Every project is synthetic: the runs were generated by driving a
virtual test article, and the "photos" are renders of the geometry,
not photographs. Open a project with File > Open, or with
visualdynamics.Project.open('...vdyn') from Python.

These are .vdyn files. The project file is provisional: the next alpha
saves projects in the Engineering Sciences Common Data Format (.escdf)
and still opens .vdyn; the first release that is not an alpha will not.
This set is re-cut when that happens.

https://visualdynamics.org/downloads
"""


def cut(out_dir: str) -> list[str]:
    """Write every zip into `out_dir`; the paths written."""
    os.makedirs(out_dir, exist_ok=True)
    written = []
    for name, (folder, projects, sentence) in SETS.items():
        source = os.path.join(ROOT, 'stressdata', folder)
        files = [os.path.join(source, f'{p}.vdyn') for p in projects]
        missing = [f for f in files if not os.path.exists(f)]
        if missing:
            sys.exit(f'not on this machine: {", ".join(missing)} — '
                     'regenerate with the generators first')
        path = os.path.join(out_dir, name)
        title = name.removeprefix('VisualDynamics-examples-').removesuffix('.zip')
        listing = ''.join(
            f'  {p}.vdyn  ({os.path.getsize(f) / 2**20:.0f} MB)\n'
            for p, f in zip(projects, files))
        with zipfile.ZipFile(path, 'w', zipfile.ZIP_DEFLATED, compresslevel=6) as z:
            z.writestr(f'{title}/README.txt', README.format(
                title=title, sentence=sentence, listing=listing))
            for p, f in zip(projects, files):
                z.write(f, f'{title}/{p}.vdyn')
        written.append(path)
        print(f'{name}: {os.path.getsize(path) / 2**20:.0f} MB')
    return written


def upload(paths: list[str]) -> None:
    """Put the zips on the `examples` release, making it if it is not
    there; an existing asset is replaced."""
    exists = subprocess.run(['gh', 'release', 'view', TAG, '--repo', REPO],
                            capture_output=True, check=False).returncode == 0
    if not exists:
        subprocess.run(
            # never "latest": the downloads page's tiles and the
            # update check's latest.json both read releases/latest,
            # and a release of zips would answer them with no
            # installer at all
            ['gh', 'release', 'create', TAG, '--repo', REPO,
             '--latest=false', '--title', 'Example projects',
             '--notes', ('Example projects for Visual Dynamics, linked from '
                         'https://visualdynamics.org/downloads — synthetic '
                         'runs on the plate and the quadcopter, one project '
                         'per workflow. Re-cut whenever the project format '
                         'moves.')],
            check=True)
    subprocess.run(['gh', 'release', 'upload', TAG, '--repo', REPO,
                    '--clobber', *paths], check=True)
    print(f'uploaded to {URL}')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    parser.add_argument('--upload', action='store_true',
                        help='put the zips on the release as well')
    parser.add_argument('--out', default=os.path.join(ROOT, 'dist', 'examples'))
    args = parser.parse_args()
    zips = cut(args.out)
    if args.upload:
        upload(zips)
