#!/usr/bin/env python
"""Cut the example projects into the zips the website links, and
upload them to the `examples` release.

    ./.venv/bin/python tools/cut_examples.py            # zips into dist/examples/
    ./.venv/bin/python tools/cut_examples.py --upload   # ...and onto the release
    ./.venv/bin/python tools/cut_examples.py --upload VisualDynamics-examples-barc.zip

The projects live in `stressdata/`, gitignored and regenerable from
the generators (testdata/generate_plate_projects.py and
generate_drone_projects.py), so they are not in any package: the
installers stay small (Brandon, 2026-09-14) and the six plate projects
and four drone projects go up as two zips on a GitHub release of
their own, which the downloads page links. A release rather than the
site because Cloudflare Pages refuses a file over 25 MB; a release of
its own rather than the application's because the examples are cut
again whenever the project format moves — the `.vdyn` format may
still change during the alpha, and a change re-cuts them without
touching an application tag. `modal_hard` stays out: 5 GB exists to
stress the fitter, not to be downloaded.

The BARC (2026-09-26, its bricks 2026-10-07) and the four-unit frame
(2026-09-30) are the exception to all of that: no runs, just models,
so their projects are
built and solved from `visualdynamics.demo.barc` and `.frame` as the
zip is cut, need nothing from `stressdata/`, and are small. Name one
zip to cut (and upload) only that one, leaving the others on the
release as they are.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import zipfile

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
REPO = 'visualdynamics/visualdynamics'
#: the release the zips live on, and the page's link target
TAG = 'examples'
URL = f'https://github.com/{REPO}/releases/download/{TAG}/'

#: how the plate's and the quadcopter's projects came to be
SYNTHETIC = """Every project is synthetic: the runs were generated by driving a
virtual test article, and the "photos" are renders of the geometry,
not photographs."""


def _barc(out_dir: str) -> None:
    """The BARC has no runs to cut: its projects are built and solved
    from the demonstration module, in seconds, on any machine — the
    model from planes the finite element workflow builds, and the
    assembly and its removable component from bricks (2026-10-07)."""
    sys.path.insert(0, os.path.join(ROOT, 'src'))
    from visualdynamics.demo import barc

    barc.project(solved=True).save(os.path.join(out_dir, 'barc.vdyn'))
    barc.solid_project(solved=True).save(
        os.path.join(out_dir, 'barc-bricks.vdyn'))


def _frame(out_dir: str) -> None:
    """The four-unit frame likewise: five models — the frame, each
    wing alone, the frame with each wing — built from blocks and solved,
    a few minutes on any machine."""
    sys.path.insert(0, os.path.join(ROOT, 'src'))
    from visualdynamics.demo import frame

    frame.project(solved=True).save(os.path.join(out_dir, 'frame.vdyn'))


#: asset name -> (where the projects come from: a folder under
#: stressdata/, or a function writing them into a folder; the projects
#: it takes; one sentence for the zip's own README; where the data came
#: from, for the README — text, or a function returning it)
SETS = {
    'VisualDynamics-examples-plate.zip': (
        'plate_projects',
        ('modal', 'random', 'shock', 'sine', 'sysid', 'transient'),
        ('The plate: a rectangular plate, one project per workflow — '
         'the same data the website\'s figures and the guide\'s '
         'screenshots come from.'),
        SYNTHETIC),
    'VisualDynamics-examples-drone.zip': (
        'drone_projects',
        ('modal', 'random', 'shock', 'transient'),
        ('The quadcopter: the same workflows on a model with the node '
         'count of a real test article.'),
        SYNTHETIC),
    'VisualDynamics-examples-frame.zip': (
        _frame,
        ('frame',),
        ('The four-unit frame: the frame, its two wings and the two '
         'assemblies as solid finite element models built from blocks of '
         'bricks and solved — a substructuring test article, checked '
         'against its measured frequencies.'),
        ('The models are visualdynamics.demo.frame, rebuilt with\n'
         'frame.project(solved=True). The frame\'s dimensions and hole\n'
         'pattern were read off the finite element models shared on the\n'
         'SEM Dynamic Substructuring Focus Group wiki,\n'
         'https://wiki.sem.org/wiki/Round_Robin_Frame_Structure, and the\n'
         'models checked against the measured frequencies there and\n'
         'against those shared models. None of the wiki\'s files are\n'
         'in this bundle.')),
    'VisualDynamics-examples-barc.zip': (
        _barc,
        ('barc', 'barc-bricks'),
        ('The BARC: a finite element model built from planes and solved '
         "— the documentation's finite element workflow, already carried "
         'out — and the BARC and its removable component built from '
         'bricks, with the bolts as point masses, solved.'),
        ('The models are visualdynamics.demo.barc, rebuilt with\n'
         'barc.project(solved=True) and barc.solid_project(solved=True).\n'
         'They were checked against the finite element models and the\n'
         'test shared on the SEM Dynamic Substructuring Focus Group wiki,\n'
         'https://wiki.sem.org/wiki/BARC, where the BARC\'s solid model,\n'
         'test data and models are. None of the wiki\'s files are in\n'
         'this bundle.')),
}

README = """Visual Dynamics example projects — {title}

{sentence}

{listing}
{about}

Open a project with File > Open, or with
visualdynamics.Project.open('...vdyn') from Python.

These are .vdyn files, the Visual Dynamics project file. While Visual
Dynamics is an alpha the .vdyn format may still change, and this set
is re-cut whenever a release changes it.

https://visualdynamics.org/downloads
"""


def cut(out_dir: str, names: list[str] | None = None) -> list[str]:
    """Write the zips named (every one, by default) into `out_dir`;
    the paths written."""
    import tempfile

    os.makedirs(out_dir, exist_ok=True)
    written = []
    for name in names or list(SETS):
        source, projects, sentence, about = SETS[name]
        about = about() if callable(about) else about
        with tempfile.TemporaryDirectory() as built:
            if callable(source):
                source(built)
                folder = built
            else:
                folder = os.path.join(ROOT, 'stressdata', source)
            files = [os.path.join(folder, f'{p}.vdyn') for p in projects]
            missing = [f for f in files if not os.path.exists(f)]
            if missing:
                sys.exit(f'not on this machine: {", ".join(missing)} — '
                         'regenerate with the generators first')
            path = os.path.join(out_dir, name)
            title = name.removeprefix('VisualDynamics-examples-').removesuffix('.zip')
            listing = ''.join(
                f'  {p}.vdyn  ({os.path.getsize(f) / 2**20:.0f} MB)\n'
                for p, f in zip(projects, files))
            with zipfile.ZipFile(path, 'w', zipfile.ZIP_DEFLATED,
                                 compresslevel=6) as z:
                z.writestr(f'{title}/README.txt', README.format(
                    title=title, sentence=sentence, listing=listing,
                    about=about))
                for p, f in zip(projects, files):
                    z.write(f, f'{title}/{p}.vdyn')
        written.append(path)
        print(f'{name}: {os.path.getsize(path) / 2**20:.0f} MB')
    return written


def upload(paths: list[str]) -> None:
    """Put the zips on the `examples` release, making it if it is not
    there; an existing asset is replaced."""
    exists = subprocess.run(['gh', 'release', 'view', TAG, '--repo', REPO],
                            capture_output=True, check=False).returncode == 0
    if not exists:
        subprocess.run(
            # never "latest": the downloads page's tiles and the
            # update check's latest.json both read releases/latest,
            # and a release of zips would answer them with no
            # installer at all
            ['gh', 'release', 'create', TAG, '--repo', REPO,
             '--latest=false', '--title', 'Example projects',
             '--notes', ('Example projects for Visual Dynamics, linked from '
                         'https://visualdynamics.org/downloads — synthetic '
                         'runs on the plate and the quadcopter, one project '
                         'per workflow, and the BARC finite element model. '
                         'Re-cut whenever the project format moves.')],
            check=True)
    subprocess.run(['gh', 'release', 'upload', TAG, '--repo', REPO,
                    '--clobber', *paths], check=True)
    print(f'uploaded to {URL}')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    parser.add_argument('--upload', action='store_true',
                        help='put the zips on the release as well')
    parser.add_argument('--out', default=os.path.join(ROOT, 'dist', 'examples'))
    parser.add_argument('sets', nargs='*', metavar='ZIP',
                        help=f'the zips to cut, of {", ".join(SETS)} '
                             '(default: every one)')
    args = parser.parse_args()
    zips = cut(args.out, args.sets)
    if args.upload:
        upload(zips)
