"""The documentation's mark and palette, taken from the app itself.

The site should look like the application it documents, and the only way
that stays true is for both to come from one definition. The colors are
read out of `visualdynamics.theme` — the same dictionaries the 3D scene
and the plots are drawn with — and the logo is `draw_app_icon`, the
function that draws the icon in the Dock and the title bar.

    python tools/make_docs_assets.py           # write docs/assets
    python tools/make_docs_assets.py --check   # fail if they are stale

`tests/test_docs_assets.py` runs the check, so the site cannot keep an
old mark or an old palette after the app has changed either.
"""

from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
ASSETS = ROOT / 'docs' / 'assets'

#: What the logo and the favicon are rendered at. The favicon is small
#: enough that `draw_app_icon` drops the element edges, which is the
#: point — sixty-four outlines over thirty pixels is a smear.
LOGO = 256
FAVICON = 64


def stylesheet() -> str:
    """Material's color variables, filled in from the app's theme.

    Only the variables that carry meaning are set. Material's own
    palettes are fine at everything else, and overriding them wholesale
    would mean maintaining a second design system to no end.
    """
    sys.path.insert(0, str(ROOT))
    from visualdynamics.plot import CURVE_COLORS
    from visualdynamics.theme import DARK, LIGHT

    # the app's first curve color is its blue — the one a single plotted
    # record wears, and the closest thing the interface has to a brand
    blue = CURVE_COLORS[0]

    def chevron(color: str) -> str:
        """Material's nav chevron as a plain background image.

        Safari renders the theme's *masked* chevron as a disc of
        uninitialized-texture noise (see the workaround below); a real
        image has no mask layer to composite. The cost is that the
        color is baked in rather than following currentColor, which is
        why there is one per scheme and state.
        """
        fill = color.replace('#', '%23')
        return ('url("data:image/svg+xml;charset=utf-8,'
                "%3Csvg xmlns='http://www.w3.org/2000/svg' "
                "viewBox='0 0 24 24'%3E%3Cpath "
                f"fill='{fill}' "
                "d='M8.59 16.58 13.17 12 8.59 7.41 10 6l6 6-6 6z'/%3E"
                '%3C/svg%3E")')
    return f"""/* Generated by tools/make_docs_assets.py from visualdynamics.theme —
   do not edit. The site wears the application's own colors: run
   `python tools/make_docs_assets.py` after changing either. */

:root {{
  --md-primary-fg-color:        {LIGHT['plot_background_top']};
  --md-primary-fg-color--light: {LIGHT['plot_background']};
  --md-primary-fg-color--dark:  {DARK['scene_background']};
  --md-primary-bg-color:        {LIGHT['plot_foreground']};
  --md-primary-bg-color--light: {LIGHT['scene_text']};
  --md-accent-fg-color:         {blue};
  --md-typeset-a-color:         {blue};
}}

/* Light: the app's own plot background, and its highlight for the
   things a reader is meant to notice. */
[data-md-color-scheme="default"] {{
  --md-default-bg-color:   {LIGHT['plot_background']};
  --md-default-fg-color:   {LIGHT['plot_foreground']};
  --md-code-bg-color:      {LIGHT['plot_background_top']};
  --md-accent-fg-color:    {LIGHT['scene_highlight']};
  /* stated here, not only on :root: the theme's own light block
     sets the link color from the primary color, which is the
     header's white — links and the navigation's current entry
     vanished in light mode (Brandon, 2026-09-04) */
  --md-typeset-a-color:    {blue};
  --md-typeset-mark-color: {LIGHT['scene_highlight']}33;
}}

/* Dark: the scene background the 3D view uses, so a screenshot of the
   app sits on the page without a seam. */
[data-md-color-scheme="slate"] {{
  --md-default-bg-color:        {DARK['scene_background_top']};
  --md-default-fg-color:        {DARK['plot_foreground']};
  --md-code-bg-color:           {DARK['scene_background']};
  --md-primary-fg-color:        {DARK['scene_background']};
  --md-primary-bg-color:        {DARK['plot_foreground']};
  --md-accent-fg-color:         {DARK['scene_highlight']};
  --md-typeset-a-color:         {DARK['scene_highlight']};
  --md-typeset-mark-color:      {DARK['scene_highlight']}33;
}}

/* A signature is read like code, so it gets the code face and enough
   room to break at the commas rather than scrolling sideways. */
.doc-signature > pre > code {{ font-size: 0.72rem; }}

/* The type column of an Attributes table is the second thing read after
   the name; the description should not crowd it out. */
.doc-contents table td:first-child {{ white-space: nowrap; }}

/* The theme colors the current page's entry in the navigation — and,
   with the table of contents folded in, the current heading's — with
   the *primary* color, which here is the header's background: black
   in dark, white in light, so the entry vanished into the sidebar
   (Brandon, 2026-09-04). It is a link; color it like one, and tint
   its background from the accent rather than the theme's own indigo. */
body[data-md-color-scheme] .md-nav__link--active,
body[data-md-color-scheme] .md-nav__link--active code {{
  color: var(--md-typeset-a-color) !important;
}}
body[data-md-color-scheme] .md-nav__link--active {{
  background-color: color-mix(in srgb, var(--md-accent-fg-color) 12%,
                              transparent) !important;
}}

/* Safari renders the sidebar's chevrons as discs of speckled noise on
   hover: the chevron is an SVG *mask* over currentColor, the hover
   affordance is a translucent circle behind it, and Safari's GPU path
   composites the pair onto a layer it never clears — uninitialized
   texture, clipped to the circle. Removing the circle and its
   transition was not enough; the mask itself has to go. The chevron
   becomes a plain image (one per scheme and hover state, since an
   image cannot follow currentColor), and the expand rotation is a
   transform, so it survives. Desktop only: the mobile drawer reuses
   .md-nav__icon for its back arrows, which are a different glyph. */
:root, [data-md-color-scheme="default"] {{
  --vd-nav-chevron:       {chevron(LIGHT['plot_foreground'])};
  --vd-nav-chevron-hover: {chevron(LIGHT['scene_highlight'])};
}}
[data-md-color-scheme="slate"] {{
  --vd-nav-chevron:       {chevron(DARK['plot_foreground'])};
  --vd-nav-chevron-hover: {chevron(DARK['scene_highlight'])};
}}
@media screen and (min-width: 76.25em) {{
  .md-sidebar .md-nav__icon {{ transition: none !important; }}
  .md-sidebar .md-nav__icon:hover {{
    background-color: transparent !important;
  }}
  .md-sidebar .md-nav__icon::after {{
    -webkit-mask: none !important;
    mask: none !important;
    background: transparent var(--vd-nav-chevron)
                center / contain no-repeat !important;
  }}
  .md-sidebar .md-nav__link:hover .md-nav__icon::after {{
    background-image: var(--vd-nav-chevron-hover) !important;
  }}
}}
"""


def icons() -> dict[str, bytes]:
    """{filename: PNG bytes} for the logo and the favicon."""
    import os

    os.environ.setdefault('QT_QPA_PLATFORM', 'offscreen')
    from PySide6.QtCore import QBuffer, QByteArray

    sys.path.insert(0, str(ROOT))
    from visualdynamics.gui.app_icon import draw_app_icon

    out = {}
    for name, size in (('logo.png', LOGO), ('favicon.png', FAVICON)):
        # the QByteArray has to outlive the QBuffer that writes into it:
        # `QBuffer(QByteArray())` hands Qt a temporary, and Python frees
        # it out from under the C++ side — a segfault, not an exception
        data = QByteArray()
        buffer = QBuffer(data)
        buffer.open(QBuffer.OpenModeFlag.WriteOnly)
        draw_app_icon(size).save(buffer, 'PNG')
        out[name] = bytes(data.data())
    return out


def build() -> dict[str, bytes]:
    """{path relative to docs/assets: contents} for every asset."""
    return {'theme.css': stylesheet().encode('utf-8'), **icons()}


def same_image(a: bytes, b: bytes) -> bool:
    """Do two PNGs draw the same picture?

    Not `a == b`: Qt's PNG encoder writes different bytes for the same
    pixels depending on whether a QApplication exists, so the file this
    tool writes from a plain interpreter never matches the one the test
    suite renders inside a Qt app — same length, same image, different
    bytes. What is being checked is the mark, so compare the mark.
    """
    from PySide6.QtGui import QImage

    first, second = QImage(), QImage()
    return (first.loadFromData(a) and second.loadFromData(b)
            and first == second)


def main(check: bool = False) -> int:
    wanted = build()
    if check:
        for name, contents in wanted.items():
            path = ASSETS / name
            if not path.exists():
                print(f'docs/assets/{name} is missing')
                return 1
            on_disk = path.read_bytes()
            same = (same_image(on_disk, contents) if name.endswith('.png')
                    else on_disk == contents)
            if not same:
                print(f'docs/assets/{name} is stale')
                return 1
        return 0
    ASSETS.mkdir(parents=True, exist_ok=True)
    for name, contents in wanted.items():
        (ASSETS / name).write_bytes(contents)
        print(f'wrote docs/assets/{name}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main('--check' in sys.argv))
