"""Four ready-to-open .vdyn projects on the drone, skeleton full.

The drone's counterpart to `generate_plate_projects.py`: the same four
workflows — modal, random vibration, transient, shock — assembled from
the drone's own runs, with every gray slot of each project type
filled. The plate is the small demonstration article the documentation
uses; this is the same set at stress size, for testing the interface
against a model that is genuinely big.

    ./.venv/bin/python testdata/generate_drone_projects.py

Writes stressdata/drone_projects/{modal,random,transient,shock}.vdyn
from stressdata/drone/, and neither directory is in the repository:
these embed hundreds of megabytes of run data. Each source that is
absent is skipped with a note rather than failing the run — the drone
data set is generated by `generate_drone.py` in the
`visualdynamics-generators` repository, which needs rattlesnake and
takes a quarter of an hour.

Every project is checked against `missing_expectations` before it is
saved: a generator whose output opens with gray slots would be writing
the very thing it exists to prevent.
"""

from __future__ import annotations

import os
import pathlib
import sys

os.environ.setdefault('QT_QPA_PLATFORM', 'offscreen')

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import numpy as np

import visualdynamics
from visualdynamics.core.photos import Photos
from visualdynamics.core.report import missing_expectations

HERE = pathlib.Path(__file__).parent
DRONE = HERE.parent / 'stressdata' / 'drone'
OUT = HERE.parent / 'stressdata' / 'drone_projects'

#: The band the runs excite (generate_drone.BAND). Everything the
#: survey can honestly say lives inside it.
BAND = (10.0, 2000.0)

#: How many modes the scripted fit takes for the stress survey. With
#: twelve references and twelve hundred channels the data can honestly
#: distinguish far more modes than the small survey's twelve — and
#: taking more is the point: the stress set exists to lean on the
#: fitting, not to be gentle with it.
HARD_MODES_FIT = 20

#: How many modes the scripted fit takes. On the screen a person stops
#: the loop; scripted, this is that judgment. The airframe has some
#: hundreds of modes below 2 kHz and twenty-four channels, which cannot
#: honestly distinguish that many — this is a survey of the bottom of
#: the band, where the modes are separated enough for twenty-four
#: channels to tell them apart.
MODES_FIT = 12

#: FEM modes kept for correlation. The full solution runs to two and a
#: half times Nyquist so the band carries the residual flexibility of
#: everything above it; correlating against modes an octave past
#: anything measured is noise with a MAC value, and keeping them all
#: put 65 MB of shapes inside a project file.
FEM_CEILING = 1.25 * BAND[1]


def photos(*scenes) -> Photos:
    """Rendered stand-ins for setup photographs: (name, geometry) pairs
    drawn offscreen and kept as PNG bytes, exactly as imported photos
    would be. Neutral studio gray, so they read as pictures of hardware
    in either app theme rather than as one broken light-mode figure."""
    import tempfile

    from visualdynamics.theme import theme as resolve_theme

    studio = dict(resolve_theme('dark'))
    studio['scene_background'] = '#6b6e74'
    studio['scene_background_top'] = '#43464c'

    names, formats, images = [], [], []
    for name, geometry in scenes:
        with tempfile.NamedTemporaryFile(suffix='.png', delete=False) as f:
            path = f.name
        geometry.plot(screenshot=path, show=False, theme=studio)
        names.append(name)
        formats.append('png')
        images.append(pathlib.Path(path).read_bytes())
        os.remove(path)
    return Photos(names=names, formats=formats, images=images)


def _defined(geometry):
    """A geometry from a .vdyn carries its own units; an older one may
    not, and a project full of undefined slots is not the point here."""
    if not geometry.units_defined:
        geometry.define_units('m')
    return geometry


def survey_geometry():
    """The display model: the nodes the test instruments, threaded with
    tracelines so an animation reads as an airframe."""
    return _defined(visualdynamics.load(str(DRONE / 'test_geometry.vdyn')))


def fem_pair():
    """The whole shell and its modes, cut to the band worth correlating."""
    geometry = _defined(visualdynamics.load(str(DRONE / 'fem_geometry.vdyn')))
    shapes = visualdynamics.load(str(DRONE / 'fem_shapes.vdyn'))
    if not shapes.units_defined:
        shapes.define_units('kg')
    beyond = [i for i, f in enumerate(np.atleast_1d(shapes.frequency))
              if f > FEM_CEILING]
    if beyond:
        shapes.delete_modes(beyond)
    return geometry, shapes


def finish(project, template, summary):
    """Report with the summary written in, then the completeness check."""
    project.generate_report(template)
    report = project.report
    for block in report.blocks:
        if block.get('kind') == 'text' and not block.get('text'):
            block['text'] = summary
            break
    missing = [(name, optional) for name, _cls, _icon, _n, optional, _role
               in missing_expectations(project.project_type, project,
                                       placed=project.placed())]
    required = [name for name, optional in missing if not optional]
    assert not required, f'{project.name}: unfilled slots {required}'
    return project


def modal_project():
    run = DRONE / 'modal_spectra.nc4'
    if not run.exists():
        print('modal_spectra.nc4 absent; skipping')
        return None
    project = visualdynamics.Project('Drone Modal Survey')
    project.project_type = 'Modal Test'
    project.import_file(str(run))
    geometry = survey_geometry()
    project.add('Geometry', geometry)
    project.add('Photos', photos(('Test article, survey layout', geometry)))
    measured = [name for name in project.names]
    project.link(*measured)
    project.set_basis(*measured)

    project.compute_psds(project.basis.time_history)
    project.fit_modes(project.basis.frf, bounds=BAND, limit=MODES_FIT,
                      name='Identified Modes')

    fem_geometry, fem_shapes = fem_pair()
    project.add('FEM Geometry', fem_geometry)
    project.add('FEM Shape Set', fem_shapes)
    project.link('FEM Geometry', 'FEM Shape Set')
    project.match_modes(project.basis.shapes, fem_shapes, threshold=0.7)
    return finish(project, 'modal', (
        'Demonstration modal survey of the quadcopter airframe: a '
        'burst-random Rattlesnake run on four shakers, twenty-four '
        'measured channels, modes identified from the measured FRFs '
        'and correlated against the finite element model.'))


def modal_hard_project():
    """The stress survey: the same workflow as `modal_project`, at
    twelve drives and twelve hundred channels — acquired in six roving
    passes against the same references, the way a survey of that size
    really runs. The spectra merge with the app's own merge rule; the
    time data stays six objects, one per pass. What stresses the
    estimation is everything downstream being the same machinery under
    a hundred and fifty times the records."""
    import glob

    passes = sorted(glob.glob(str(DRONE / 'modal_hard_p*_spectra.nc4')))
    if not passes:
        print('modal_hard_p*_spectra.nc4 absent; skipping '
              '(generate_drone.py --modal_hard)')
        return None
    project = visualdynamics.Project('Drone Modal Survey (Stress)')
    project.project_type = 'Modal Test'

    from visualdynamics.core.channel_table import ChannelTable
    from visualdynamics.core.data import (
        Frf,
        MultipleCoherence,
        TimeHistory,
    )

    # The time data is NOT merged (Brandon, 2026-08-29). Each pass is
    # its own acquisition: its accelerations were caused by its own
    # force realizations, and the pairing between them is the whole
    # meaning of the records. A merged object numbered forces 1-120
    # against accelerations 1-20 and kept the pairing only as row
    # order, which nothing reads — a record that could never have been
    # measured. The FRFs were computed per pass, from matched data,
    # before any merge; those merge honestly, as disjoint sets.
    imported: dict[type, list[str]] = {}
    for k, path in enumerate(passes, 1):
        for name in project.import_file(path):
            obj = project[name]
            if isinstance(obj, TimeHistory):
                name = project.rename(name, f'Time History Pass {k}')
            imported.setdefault(type(obj), []).append(name)
    merged = list(imported.pop(TimeHistory, []))
    for kind in (Frf, MultipleCoherence, ChannelTable):
        names = imported.pop(kind, [])
        if len(names) > 1:
            # same disjoint-records rule as the FRFs: each pass holds
            # its own response DOFs against the same twelve references
            merged.append(project.merge(*names, name=kind.__name__))
        elif names:
            merged.append(names[0])
    # whatever else the import brought rides along un-merged
    merged += [name for names in imported.values() for name in names]

    geometry = _defined(
        visualdynamics.load(str(DRONE / 'hard_geometry.vdyn')))
    project.add('Geometry', geometry)
    project.add('Photos', photos(('Test article, stress layout', geometry)))
    everything = [name for name in project.names]
    project.link(*everything)
    project.set_basis(*everything)

    # one PSD set per pass, from that pass's own records — the same
    # reason the time data stays separate
    for k in range(1, len(passes) + 1):
        project.compute_psds(f'Time History Pass {k}')
    project.fit_modes(project.basis.frf, bounds=BAND, limit=HARD_MODES_FIT,
                      name='Identified Modes')

    fem_geometry, fem_shapes = fem_pair()
    project.add('FEM Geometry', fem_geometry)
    project.add('FEM Shape Set', fem_shapes)
    project.link('FEM Geometry', 'FEM Shape Set')
    project.match_modes(project.basis.shapes, fem_shapes, threshold=0.7)
    return finish(project, 'modal', (
        'Stress-scale modal survey of the quadcopter airframe: twelve '
        'shakers against twelve hundred measured degrees of freedom — '
        'three axes at four hundred nodes covering every part of the '
        'airframe, propellers included — acquired in six roving passes '
        'of burst random against fixed references. Each pass keeps its '
        'own time data; the per-pass FRFs are merged into one set, '
        'modes identified from it and correlated against the finite '
        'element model.'))


def random_project():
    run = DRONE / 'random.nc4'
    if not run.exists():
        print('random.nc4 absent; skipping')
        return None
    project = visualdynamics.random_vibration_run(str(run))
    geometry = survey_geometry()
    project.add('Geometry', geometry)
    project.add('Photos', photos(('Test article', geometry)))
    project.link(*[name for name in project.names])
    project.set_basis(*[name for name in project.names])
    # no compute calls: random_vibration_run already worked the run up
    # — PSDs, the octave banding, the coherence
    return finish(project, 'random', (
        'Demonstration random vibration test of the quadcopter '
        'airframe: sixteen control channels against four shakers, '
        'controlled to a shaped acceleration specification.'))


def transient_project():
    run = DRONE / 'transient.nc4'
    if not run.exists():
        print('transient.nc4 absent; skipping')
        return None
    project = visualdynamics.Project('Drone Transient Replication')
    project.import_file(str(run))
    assert project.project_type == 'Transient', project.project_type
    geometry = survey_geometry()
    project.add('Geometry', geometry)
    project.add('Photos', photos(('Test article', geometry)))
    project.link(*[name for name in project.names])
    project.set_basis(*[name for name in project.names])
    # the spectral pair: the target's own PSD arrives as a
    # specification, the measurement's as data. No SRS — that
    # judgment belongs to the shock type
    project.compute_psds(project.transient_specification)
    project.compute_psds(project.time_history)
    return finish(project, 'transient', (
        "Demonstration transient replication on the quadcopter "
        "airframe: the target waveform is the drone's own response to "
        'a burst at a motor mount, replicated by four shakers across '
        'sixteen control channels.'))


def shock_project():
    run = DRONE / 'shock.nc4'
    if not run.exists():
        print('shock.nc4 absent — run generate_drone.py --shock first '
              '(visualdynamics-generators); skipping')
        return None
    project = visualdynamics.Project('Drone Shock Series')
    project.import_file(str(run))
    # a shock recording is indistinguishable from a transient at the
    # file level — the run arrives as Transient and the engineer says
    # what the test was
    project.project_type = 'Shock'
    geometry = survey_geometry()
    project.add('Geometry', geometry)
    project.add('Photos', photos(('Test article', geometry)))
    project.link(*[name for name in project.names])
    project.set_basis(*[name for name in project.names])

    # The recommended shock workflow, in order (Brandon, 2026-08-25):
    # the recording is filtered first, and everything judged is
    # computed from the *filtered* record — the SRS, the density, and
    # the motion chain alike. Filtering after computing would leave
    # three answers that disagree about which record they describe.
    #
    # The corner is the record's own suggestion, a tenth of the
    # sample rate: the frequency where the integrate/differentiate
    # round trip was measured at about 2% (core.filters), and above
    # any content a shock specification is written to.
    raw = project.time_history
    # the events are marked on the *recording*, before anything is
    # derived from it: `core.filters` carries the marks onto whatever
    # it makes, so the filtered record, its SRS and its motion all
    # number the same events. Detecting after the filter instead left
    # the recording itself unmarked, and the report's own summary —
    # which counts the events on the recording — had nothing to count
    project.detect_shocks(raw)
    filtered = project.filter_data(raw)
    srs_name = project.compute_srs(filtered)
    velocity = project.integrate(filtered)
    project.integrate(velocity)
    project.compute_psds(filtered)
    srs = project[srs_name]

    # the requirement the series was walked up against: a tolerance
    # band around the final event's spectrum, authored the way a shock
    # specification is — breakpoints, not a copied curve
    from visualdynamics.core.data import ShockSpecification

    frequencies = np.asarray(srs.abscissa, dtype=float)
    top = np.asarray(srs.ordinate, dtype=float).max(axis=0)
    level = 10.0 ** np.interp(np.log10(frequencies),
                              np.log10([frequencies[0], 200.0, 2000.0,
                                        frequencies[-1]]),
                              np.log10([top.max() * 0.05, top.max() * 0.9,
                                        top.max() * 1.1, top.max() * 1.1]))
    project.add('Shock Specification', ShockSpecification(
        abscissa=frequencies, ordinate=level[None, :],
        response_dof=[srs.response_dof[0]],
        ordinate_dim='acceleration', ordinate_unit='m/s**2',
        q=srs.q, kind=srs.kind,
        abort_upper=level[None, :] * 10.0 ** 0.3,
        abort_lower=level[None, :] * 10.0 ** -0.3))
    project.link(*[name for name in project.names])
    project.set_basis(*[name for name in project.names])
    return finish(project, 'shock', (
        'Demonstration shock series on the quadcopter airframe: four '
        'half-sine events walked up to level, judged by their shock '
        'response spectra against the specification band.'))


def main(which=('modal', 'random', 'transient', 'shock')):
    OUT.mkdir(parents=True, exist_ok=True)
    for build in (modal_project, modal_hard_project, random_project,
                  transient_project, shock_project):
        name = build.__name__.replace('_project', '')
        if name not in which:
            continue
        project = build()
        if project is None:
            continue
        path = OUT / f'{name}.vdyn'
        project.save(str(path))
        print(f'{path.name}: {len(project)} objects, '
              f'{path.stat().st_size / 1e6:.1f} MB', flush=True)


if __name__ == '__main__':
    picked = tuple(a.lstrip('-') for a in sys.argv[1:])
    main(picked or ('modal', 'random', 'transient', 'shock'))
